TravisCI: test yaml anchors with jobs

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,95 +6,100 @@ addons:
       - docker-xenial
 
 env:
-  matrix:
-  # Activate only Supported and Nightly Images.
-  - FOLDER=2.4.nightly-ubuntu
-  - FOLDER=2.4.nightly-debian 
-    ADD_TAGS="latest"
-  - FOLDER=2.4.88-ubuntu
-  - FOLDER=2.4.89-ubuntu
-  - FOLDER=2.4.90-ubuntu
-  - FOLDER=2.4.91-ubuntu
-  - FOLDER=2.4.92-ubuntu
-  - FOLDER=2.4.93-ubuntu
-  - FOLDER=2.4.94-ubuntu
-  - FOLDER=2.4.95-ubuntu
-  - FOLDER=2.4.96-ubuntu
-  - FOLDER=2.4.97-debian
-  - FOLDER=2.4.98-debian
-  - FOLDER=2.4.99-debian
-  - FOLDER=2.4.100-debian
-  - FOLDER=2.4.101-debian
-  - FOLDER=2.4.102-debian
-  - FOLDER=2.4.103-debian
-  - FOLDER=2.4.104-debian
-  - FOLDER=2.4.105-debian
-  - FOLDER=2.4.106-debian
-  - FOLDER=2.4.107-debian
-  - FOLDER=2.4.108-debian
-  - FOLDER=2.4.109-debian
   global:
   #- DOCKER_COMPOSE_VERSION=1.4.2
   - COMPONENT=server
 
-jobs:
-  include:
-    - stage: test
-      before_script:
-        # Build
-        - export CONTAINER_NAME="$(echo $TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]')"
-        - docker build
-            --build-arg "VCS_REF=$TRAVIS_COMMIT" 
-            --build-arg "VERSION=$(echo $FOLDER |cut -d - -f 1)" 
-            --build-arg "GIT_REPO=https://github.com/$CONTAINER_NAME" 
-            --build-arg "COMPONENT=$COMPONENT"
-            --build-arg "BUILD_DATE=$(date -u +"%Y-%m-%d")"
-            -t "$CONTAINER_NAME:$FOLDER-dev"
-            "$TRAVIS_BUILD_DIR/$FOLDER/"
-        - docker images
-        # PUSH
-        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
-        - echo "" && [ "$TRAVIS_BRANCH" = "feat/MDD-151" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && docker push "$CONTAINER_NAME:$FOLDER-dev";
+stages:
+- test
+- notify
 
-        # Retag Images and push
-        - echo "" && [ "$TRAVIS_BRANCH" = "feat/MDD-151" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && for i in $ADD_TAGS; do docker tag "$CONTAINER_NAME:$FOLDER-dev" "$CONTAINER_NAME:$i"; docker push "$CONTAINER_NAME:$i"; done
-    - stage: notify
-      script: 
-        # Notify
-        - set -xv
-        # Set ret_value variable with the result of curl command
-        - ret_value="$(curl -X POST -H "Content-Type':' application/json"  --data '{"docker_tag_name"':' "hub_automatic_untested"}'  "$DOCKER_HUB_NOTIFY_URL")"
-        # Check if curl command was successful
-        - if [ -z "$("$ret_value"|grep "state"':'"Success")" ] || [ -z "$("$ret_value"|grep "state"':'"Building")" ]; then echo "Failure':' $ret_value"; exit 1; fi;
-        - echo "Build end."
+- &build
+  stage: test
+  script: >
+    # Build
+    export CONTAINER_NAME="$(echo $TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]')"
+    docker build \
+        --build-arg "VCS_REF=$TRAVIS_COMMIT"  \
+        --build-arg "VERSION=$(echo $FOLDER |cut -d - -f 1)"  \
+        --build-arg "GIT_REPO=https://github.com/$CONTAINER_NAME"  \
+        --build-arg "COMPONENT=$COMPONENT" \
+        --build-arg "BUILD_DATE=$(date -u +"%Y-%m-%d")" \
+        -t "$CONTAINER_NAME:$FOLDER-dev" \
+        "$TRAVIS_BUILD_DIR/$FOLDER/"
+    docker images
+    # PUSH
+    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
+    echo "" && [ "$TRAVIS_BRANCH" = "feat/MDD-151" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && docker push "$CONTAINER_NAME:$FOLDER-dev";
+    # Retag Images and push
+    echo "" && [ "$TRAVIS_BRANCH" = "feat/MDD-151" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && for i in $ADD_TAGS; do docker tag "$CONTAINER_NAME:$FOLDER-dev" "$CONTAINER_NAME:$i"; docker push "$CONTAINER_NAME:$i"; done
 
-# before_script:
-# # Build
-# - export CONTAINER_NAME="$(echo $TRAVIS_REPO_SLUG | tr '[:upper:]' '[:lower:]')"
-# - docker build
-#     --build-arg "VCS_REF=$TRAVIS_COMMIT" 
-#     --build-arg "VERSION=$(echo $FOLDER |cut -d - -f 1)" 
-#     --build-arg "GIT_REPO=https://github.com/$CONTAINER_NAME" 
-#     --build-arg "COMPONENT=$COMPONENT"
-#     --build-arg "BUILD_DATE=$(date -u +"%Y-%m-%d")"
-#     -t "$CONTAINER_NAME:$FOLDER-dev"
-#     "$TRAVIS_BUILD_DIR/$FOLDER/"
-# - docker images
+- &noitfy
+  stage: notify
+  script: >  
+    # Notify
+    set -xv
+    # Set ret_value variable with the result of curl command
+    ret_value="$(curl -X POST -H "Content-Type':' application/json"  --data '{"docker_tag_name"':' "hub_automatic_untested"}'  "$DOCKER_HUB_NOTIFY_URL")"
+    # Check if curl command was successful
+    if [ -z "$("$ret_value"|grep "state"':'"Success")" ] || [ -z "$("$ret_value"|grep "state"':'"Building")" ]; then echo "Failure':' $ret_value"; exit 1; fi;
+    echo "Build end."
 
-# # PUSH
-# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
-# - echo "" && [ "$TRAVIS_BRANCH" = "feat/MDD-151" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && docker push "$CONTAINER_NAME:$FOLDER-dev";
+#################################
 
-# # Retag Images and push
-# - echo "" && [ "$TRAVIS_BRANCH" = "feat/MDD-151" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && for i in $ADD_TAGS; do docker tag "$CONTAINER_NAME:$FOLDER-dev" "$CONTAINER_NAME:$i"; docker push "$CONTAINER_NAME:$i"; done
-# # Notify
-# - set -xv
-# # Set ret_value variable with the result of curl command
-# - ret_value="$(curl -X POST -H "Content-Type':' application/json"  --data '{"docker_tag_name"':' "hub_automatic_untested"}'  "$DOCKER_HUB_NOTIFY_URL")"
-# # Check if curl command was successful
-# - if [ -z "$("$ret_value"|grep "state"':'"Success")" ] || [ -z "$("$ret_value"|grep "state"':'"Building")" ]; then echo "Failure':' $ret_value"; exit 1; fi;
-# - echo "Build end."
 
-# don't notify me when things fail 
-#notifications:
-#  email: false
+# Notify
+- <<: *notify
+  FOLDER: 2.4.88-ubuntu
+
+# Nightly Builds
+- <<: *build
+  FOLDER: 2.4.nightly-ubuntu
+- <<: *build
+  FOLDER: 2.4.nightly-debian
+  ADD_TAGS: "latest"
+# Release Builds
+- <<: *build
+  FOLDER: 2.4.88-ubuntu
+- <<: *build
+  FOLDER: 2.4.89-ubuntu
+- <<: *build
+  FOLDER: 2.4.90-ubuntu
+- <<: *build
+  FOLDER: 2.4.91-ubuntu
+- <<: *build
+  FOLDER: 2.4.92-ubuntu
+- <<: *build
+  FOLDER: 2.4.93-ubuntu
+- <<: *build
+  FOLDER: 2.4.94-ubuntu
+- <<: *build
+  FOLDER: 2.4.95-ubuntu
+- <<: *build
+  FOLDER: 2.4.96-ubuntu
+- <<: *build
+  FOLDER: 2.4.97-debian
+- <<: *build
+  FOLDER: 2.4.98-debian
+- <<: *build
+  FOLDER: 2.4.99-debian
+- <<: *build
+  FOLDER: 2.4.100-debian
+- <<: *build
+  FOLDER: 2.4.101-debian
+- <<: *build
+  FOLDER: 2.4.102-debian
+- <<: *build
+  FOLDER: 2.4.103-debian
+- <<: *build
+  FOLDER: 2.4.104-debian
+- <<: *build
+  FOLDER: 2.4.105-debian
+- <<: *build
+  FOLDER: 2.4.106-debian
+- <<: *build
+  FOLDER: 2.4.107-debian
+- <<: *build
+  FOLDER: 2.4.108-debian
+- <<: *build
+  FOLDER: 2.4.109-debian
